dubbo:
  application:
    name: cart-service
  registry:
    protocol: zookeeper
    address: 120.27.243.183:2181
  protocol:
    port: 20884
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/v16?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10

  redis:
    host: 120.27.243.183
    port: 6379
    password: java1904
    jedis:
      pool:
        max-active: 66
server:
  port: 8083


