dubbo:
  application:
    name: user-service
  registry:
    protocol: zookeeper
    address: 120.27.243.183:2181

server:
  port: 9096

spring:
  thymeleaf:
    cache: false


  dubbo:
    application:
      name: product-service
    registry:
      protocol: zookeeper
      address: 120.27.243.183:2181
